[passwords]
login_me = "LoginMe"
password_me = "Instr.1D4SHUnger!"

login_prova = "LoginProva"
password_prova = "Instr.2D4SHUnger!"

login_gianluca = "LoginGianluca"
password_gianluca = "unger.D4SHInstr1!"